### PR TITLE
update neo-cli version to 2.161.3

### PR DESCRIPTION
**Pull request by alexanderparr**

### CODE REVIEW

**Comment by alexanderparr** [comment]
Hi @fwilhe, @1084565,
what are the next steps to get this PR merged?
Are these CI Tests supposed to work?
Is there anything I can do from my side?

Best
Alex

**Comment by fwilhe** [comment]
Hi @alexanderparr,

due to secret handling, the tests can only work if they are run from a branch on the upstream repo. I have pushed your commit to a branch to run them, and I'm not quite sure why they still failed with this message. Will look into it. There is nothing you need to do.

**Comment by alexanderparr** [comment]
Hi all,
is there any update on this PR?

Best
Alex

**Comment by 1084565** [comment]
Hi @alexanderparr 
the voter is still failing 

@radsoulbeard @fwilhe could you have a look at this error in this PR? #109

**Comment by fwilhe** [comment]
Hi @alexanderparr, sorry this PR was open for so long, but we have now split the repos (which also improves the CI situation), and the new image at https://github.com/SAP/devops-docker-neo-cli/blob/master/Dockerfile already includes a newer version of the CLI, so this PR is obsolete as of now.

**Pull request closed without merging**
