### PR TITLE
add Docker lint action

### PR DESCRIPTION
**Pull request by CCFenner**
Add [Github Action](https://github.com/cds-snc/github-actions/tree/master/docker-lint) to lint Dockerfiles with [HaDoLint](https://github.com/hadolint/hadolint).

https://developer.github.com/actions/

ignored rules:
- DL3008
- DL3013
- DL3016
- DL3018

### CODE REVIEW

**Comment by CCFenner** [comment]
Actions are canceled if one fails (fail fast), this should be changed.

**Comment by fwilhe** [comment]
I like this, thanks for the initiative.

Probably failing the build is a bit too much for suggestions like pinning versions in `apt-get` commands. Is there some option to only fail on 'fatal' errors?

**Comment by CCFenner** [comment]
> Is there some option to only fail on 'fatal' errors?

Not that I know, but the Voter is not mandatory.

**Comment by fwilhe** [comment]
Ok, I'd then like to [ignore some warnings which is possible](https://github.com/hadolint/hadolint/blob/master/README.md#configure), so that's ok with me.

**Comment by CCFenner** [comment]
So any suggestions for *global* ignores or are you fine with doing it inline?

```
# hadolint ignore=DL3003,SC1035
RUN cd /tmp && echo "hello!"
```

**Comment by fwilhe** [comment]
I think we could ignore DL3008 DL3018 globally, the rest seems like a case-by-case decision to me atm.

**Comment by CCFenner** [comment]
What about the same rule for NPM? 
DL3016

**Comment by fwilhe** [comment]
> What about the same rule for NPM?
> DL3016

Did not notice that one, but I guess the same argument applies there. 👍

**Comment by CCFenner** [comment]
Can I merge it like this? I now need a review to do.

**Pull request merged**
