### PR TITLE
WIP: Add bash to alpine image

### PR DESCRIPTION
**Pull request by 1084565**
Without bash the container won't run on Azure Devops.
cf. [Azure doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml)

### CODE REVIEW

**Comment by 1084565** [comment]
`The job exceeded the maximum time limit for jobs, and has been terminated.`

Does anybody @SAP/jenkins-team2 have an idea why?

**Comment by fwilhe** [comment]
> `The job exceeded the maximum time limit for jobs, and has been terminated.`
> 
> Does anybody @SAP/jenkins-team2 have an idea why?

Did not have a close look, but I've had this happen before. Will improve when we have the repo split because less load will be on travis. Would try to rerun.

**Comment by fwilhe** [comment]
Is this required? If so, please open in the new repo.

**Comment by 1084565** [comment]
Yes, I will, just give me a couple of days.

**Comment by fwilhe** [comment]
Merged in new repo

**Pull request closed without merging**
