### PR TITLE
container-structure-test: remove HaDoLint findings

### PR DESCRIPTION
**Pull request by CCFenner**
remove HaDoLint findings:
- [x] Dockerfile:4 DL3007 Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag
- [x] Dockerfile:5 DL3022 COPY --from should reference a previously defined FROM alias
- [x] Dockerfile:6 DL3022 COPY --from should reference a previously defined FROM alias

related issue: #72

### CODE REVIEW

**Comment by CCFenner** [comment]
@OliverNocon do we want to keep `latest` tag?

**Comment by OliverNocon** [comment]
Yes, let's keep latest for now

**Comment by fwilhe** [comment]
> Yes, let's keep latest for now

I'd vote for ignoring this as of now, same thing in the Jenkinsfile runner. Just not worth the effort at the moment.

**Comment by CCFenner** [comment]
@fwilhe any idea why the tests are failing?

**Comment by fwilhe** [comment]
> @fwilhe any idea why the tests are failing?

They fail since friday, was hoping it would work again. I've seen various errors that all look like some kind of infrastructure issue, file transfers don't work. I'll have a look if the same kind of issue is also there on azure to see if it is travis related or not.

**Comment by marcusholl** [comment]
>  I'll have a look if the same kind of issue is also there on azure to see if it is travis related or not.

I doubt that this kind of issue will be solved by an infrastructure shift. E.g. failures caused by exeeded quotas, or failures caused by parallel deployments will not vanish when moving from one  central build infrastrucure to another ...

IMO we should try to establish mocking for the remote systems. E.g. wiremock. We had already a closer look to wiremock on our side. In conjunction with neo there are some https handshake issues (or similar: no cipher suites in common) which we did not solve up to now. Nevertheless: IMO it would be more reasonable to think about mocking here than thinking about moving to another build infrastructure.

For the sake of completeness: now one might say: "Mocking, nice but: we would like to to have it really end-to-end." I understand that, but the kind of errors we receive has a long history. IMO it is better to mock and to have from time to time on a regular basis additionally manual tests, fully end to end. In case you work with mocks you need to do this anyway in order to verify that your mocks are still valid. When using wiremock (... I'm not on their payroll, by the way) you can do this by setting the wiremock server to a proxy mode, forwarding the traffic to a real backend (... and of course recording both, the requests and the responses).

**Comment by fwilhe** [comment]
I see your point @marcusholl, but I'm hesitant to surrender the end-to-end automated test. In the end, my requirement is to be confident in the automated tests we have. A test that fails due to infrastructure issues is annoying and costs time, but does not nearly harm as much as a mocked test which does not find a legit defect.

**Pull request merged**
